FROM mx3_deb9_qt4


ENV DEBIAN_FRONTEND noninteractive
## install mysql server 
#RUN apt-get install -y default-mysql-server
##install tango-db 
#RUN apt-get install -y tango-db
##install tango-test DS 
#RUN apt-get install -y tango-test
## install sardana dependencies
#RUN apt-get install -y python-pytango
#ENV TANGO_HOST=localhost:10000 

RUN apt-get install -y python-sardana

